name = "kick00123"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "77.91.69.238:2053"
UUID = "eb845fc2-9193-4326-9cc1-02246f61fb29"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
