name = "kick00123"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "776f50e2-1989-46fd-94de-ec5b5491da79"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
